### ISSUE TITLE
fifth

### ISSUE THREAD

**Issue by jon1enforce** [kashikoibumi/PyBitmessage#10]
The foldertree.py issue is somewhat about qt -- migration: If it is a bug, not a feature:

Looks like QtCore.QByteArray() and how to convert it into integer..?
first) int.from_bytes(timestamp, 'utf-8') is wrong
second) int(timestamp) much more wrong

...the timestamp...

https://stackoverflow.com/questions/1251662/qbytearray-to-integer

**Comment by jon1enforce** [comment]
could not load message from disk 
a bug or a feature?

**Comment by kashikoibumi** [comment]
This should be fixed by bdbe5cca616148e3ae3303b7572675d0c96c05b1 .
Sorry, this is my careless mistake on indexing data columns.
Binary msgid was wrongly substituted to the timestamp parameter.
