### ISSUE TITLE
first

### ISSUE THREAD

**Issue by jon1enforce** [kashikoibumi/PyBitmessage#2]
fix __init__.py
  File "/usr/local/lib/python3.7/dist-packages/pybitmessage/bitmessageqt/__init__.py", line 2418
 ---  label = unic(ustr(config.get(addressInKeysFile, 'label')).strip()) or addressInKeyFile
+++ label = unic(ustr(config.get(addressInKeysFile, 'label')).strip()) or addressInKeysFile

**Comment by kashikoibumi** [comment]
Fixed.
Thanks!
