### ISSUE TITLE
third 

### ISSUE THREAD

**Issue by jon1enforce** [kashikoibumi/PyBitmessage#6]
---SaveConfigParser

just..

+++ConfigParser

**Comment by kashikoibumi** [comment]
I guess you mean SafeConfigParser.
Anyway, six.moves is used for Python2 / Python3 compatibility, so I think this should be untouched.
My port is intended to run not only with Python3 but also with good old Python2.

**Comment by jon1enforce** [comment]
this issue depends on python 3.12 (maybe also 3.11) at alpine linux -- it does not raised by python 3.7 at devuan linux(your test environment).
And on openbsd and freebsd it is still not connecting, but runs offline.(thats why i looked at the flowcharts, because openbsd and freebsd are very reliable, so i wondered.)
i assume SafeConfigParser is deprecated at python 3.12 because it is  simply disabled - through this error. i did not use python2 on your code, but nice to know.
There is no attribute SafeConfigParser, because the namespace changed to ConfigParser instead of SafeConfigParser, since 3.12, i guess. It makes no sense for me, but iam not a python developer.
+++
..maybe somewhat like...(bmconfigparser.py line 19)

if sys.version.info[0] == '3' and sys.version.info[1] >= int('11') ###or sys.version.info[1] ==  '12': 
    SafeConfigParser = configparser.ConfigParser
else:
    SafeConfigParser = configparser.SafeConfigParser
+++

,to keep the compability.

**Comment by kashikoibumi** [comment]
Thanks for your detailed report!
In my development environment, Python version is 3.11.2 and works without problems, so the change may be introduced by version 3.12 .
I will update the code along your suggestion soon.

**Comment by kashikoibumi** [comment]
My grep shows SafeConfigParser is referenced by:
* src/bitmessageqt/settings.py
* src/bmconfigparser.py

Both of files should be treated.

By the way, how about using exception instead of checking version, such as:
```
try:
    SafeConfigParser = configparser.SafeConfigParser
except AttributeError:
    SafeConfigParser = configparser.ConfigParser
```
I have learned that this kind of idioms are prevalent in Python world.

**Comment by kashikoibumi** [comment]
Updated: 909b9f2c8e55e45b2b138a3b0ae7c06d6a5b77c6
(I forgot to add issue tag on commit message..)
If you have time, please test again :)

**Comment by jon1enforce** [comment]
Tested, and works now on alpine linux python3.12, without problems!
+++
it is a compability feature, so it should looks like that; and sys.version_info() is a eyecatcher for compability. But let's agree on yours with comment: 
`
>try:
>    SafeConfigParser = configparser.SafeConfigParser
>except AttributeError:
>    SafeConfigParser = configparser.ConfigParser
>    #alpine linux, python3.12
`
,so it is reminded for future


CLOSED

**Comment by kashikoibumi** [comment]
Updated: 45d1c62f97539f20861bef8274e66b434e04ea5c
(I forgot to add issue tag on commit message again..) >_<
Comments are added.
Thanks!
